import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainArea from "@/components/MainArea/MainArea";
import HeaderArea from "@/components/HeaderArea/HeaderArea";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderArea />
        <MainArea>{children}</MainArea>
      </body>
    </html>
  );
}
